---
version: '3'

env:
  SSH_KEY: id_rsa
  ASDF_VERSION: 1.3.1

tasks:
  setup:
    deps: [lint, mac, dirs, files, init, brew, asdf, default-venv, mac-brew-pkgs, vlang]

  dirs:
    cmds:
      - mkdir -p ${HOME}/.aws
      - mkdir -p ${HOME}/.ssh
      - mkdir -p ${HOME}/.kube
      - mkdir -p ${HOME}/.vscode
      - mkdir -p ${HOME}/.cargo
      - mkdir -p ${HOME}/git
      - mkdir -p ${HOME}/go
      - mkdir -p ${HOME}/bin
      - mkdir -p ${HOME}/tmp
      - mkdir -p ${HOME}/venvs

  # theory: these should use git as the source of truth
  # and distribute the files to your local filesystem
  files:
    deps: [dirs]
    cmds:
      - cp files/dotprofile ${HOME}/.zprofile
      - cp files/dotprofile ${HOME}/.bash_profile
      - cp asdf-config/.tool-versions ${HOME}/.tool-versions
      - cp asdf-config/.plugin-versions ${HOME}/.plugin-versions
      - cp files/oh-my-posh.omp.json ${HOME}/oh-my-posh.omp.json
      - cp files/vimrc ${HOME}/.vimrc
      - cp files/.gitconfig ${HOME}/.gitconfig
      - echo "Don't forget to run source ~/.zprofile or source ~/.bash_profile"

  # theory: these are more destructive actions that should
  # only be run to bootstrap your env. please run cp with -n (no clobber)
  init:
    deps: [dirs]
    cmds:
      - cp -n files/aws-config ${HOME}/.aws/config || echo "File already present"
      - cp -n files/ssh-config ${HOME}/.ssh/config || echo "File already present"
      - cp -n .envrc ${HOME}/git/.envrc || echo "File already present"

  # installs the required plugin for asdf that allows
  # us to manage everything else as a plugin definition
  asdf:
    cmds:
      - asdf plugin add asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git
      - asdf plugin update asdf-plugin-manager v{{ .ASDF_VERSION }}
      - asdf plugin-add direnv # direnv plugin via asdf-plugin-manager is broken....
      - asdf install asdf-plugin-manager {{ .ASDF_VERSION }} # installs the plugin manager cli
      - asdf global asdf-plugin-manager {{ .ASDF_VERSION }} # Set a version globally (on your ~/.tool-versions file)
      - rm -rf /tmp/asdf-temp && mkdir -p /tmp/asdf-temp # running from a temp dir because asdf plugin manager seems to like a non-git directory to run in
      - cp -r asdf-config/.*-versions /tmp/asdf-temp/
      - cd /tmp/asdf-temp/ && ${HOME}/.asdf/installs/asdf-plugin-manager/{{ .ASDF_VERSION }}/bin/asdf-plugin-manager add-all
      - cd /tmp/asdf-temp/ && asdf install
      - rm -rf /tmp/asdf-temp # clean up our temp dir
      - asdf direnv setup --shell $SHELL --version latest || echo "TODO - Ignore error here for now, direnv plugin is broken"

  default-venv:
    deps: [dirs]
    cmds:
      - python -m venv ${HOME}/venvs/py3-venv
      - source ${HOME}/venvs/py3-venv/bin/activate
      - python -m ensurepip --upgrade || echo "Ignore errors"
      - pip install -r files/py3-pip-requirements.txt

  ssh-key:
    deps: [dirs, files]
    prompt: This is a dangerous command... Do you want to continue? Backup your old ssh key(s) first.
    cmds:
      - chmod 700 $HOME/.ssh
      - chmod 644 $HOME/.ssh/config || echo "Doesn't exist yet, skipping"
      - ssh-keygen -t rsa -b 4096 -f $HOME/.ssh/{{ .SSH_KEY }}
      - chmod 600 $HOME/.ssh/{{ .SSH_KEY }}
      - ssh-keygen -y -f $HOME/.ssh/{{ .SSH_KEY }} > $HOME/.ssh/{{ .SSH_KEY }}.pub
      - chmod 644 $HOME/.ssh/{{ .SSH_KEY }}.pub
    requires:
      vars: [SSH_KEY]

  mac:
    platforms: [darwin]
    cmds:
      - xcode-select --install || echo "Already installed"
      - curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg" && sudo installer -pkg AWSCLIV2.pkg -target / && rm AWSCLIV2.pkg

  brew-pkgs:
    aliases: [brew]
    cmds:
      - for: [
        warrensbox/tap/tfswitch, warrensbox/tap/tgswitch, tz, act, agg,
        asciinema, asdf, bash, kubectl, exiftool, ffmpeg, gh, git, git-lfs,
        grep, glow, gnu-sed, go, go-task, node, npm, gcc, llvm, maven,
        jsonlint, helm, helmfile, helmify, jq, k3d, kind,
        kubernetes-cli, librtlsdr, mcfly, podman, proxychains-ng,
        rustup-init, danielfoehrkn/switch/switch, tor, tree, yq, yt-dlp, watch, tmux, yamllint,
        pwgen, azure-cli, glab, gawk, k3d, k9s, lazygit, mkcert, openssh,
        opentofu, sops, skaffold, typescript
      ]
        task: brew-install
        vars:
          PKG: '{{.ITEM}}'

  brew-install:
    internal: true
    cmds:
      - brew install {{.PKG}}

  mac-brew-pkgs:
    platforms: [darwin]
    cmds:
      - for: [sergiobenitez/osxct/x86_64-unknown-linux-gnu, telnet]
        task: brew-install
        vars:
          PKG: '{{.ITEM}}'

  vlang:
    deps: [dirs]
    cmds:
      - cd ${HOME}/git && git clone https://github.com/vlang/v || echo "Skip if already cloned"
      - cd ${HOME}/git/v && make
      - cd ${HOME}/git/v && sudo ./v symlink

  lint:
    cmds:
      - yamllint --no-warnings *.yml
      - yamllint --no-warnings .github/workflows/*.yml
      - yamllint --no-warnings .yamllint
