version: '3'

tasks:
  setup:
  # installs the required plugin for asdf that allows us to manage everything else as a plugin definition
    cmds:
      - asdf plugin add asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git
      - asdf plugin update asdf-plugin-manager v1.3.1
      - asdf install asdf-plugin-manager 1.3.1 # installs the plugin manager cli
      - asdf global asdf-plugin-manager 1.3.1 # Set a version globally (on your ~/.tool-versions file)
      - asdf-plugin-manager add-all
      - asdf install
