---
name: YAML Lint

on:
  push:
    branches:
      - '**'

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: actionshub/yamllint@v1.8.2
